### ISSUE TITLE
Please transfer this to perl6 org

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/z#5]
I love this thing but it's currently not working due to changes in `*_REVISION` file locations. I'd like to fix it but have no write permissions. I think it'd be better to move this repo to perl6 org.

**Comment by zoffixznet** [comment]
I don't have perl6 org perms to transfer to it. I tried transferring to you, but got an error saying "AlexDaniel/z already exists "

**Comment by AlexDaniel** [comment]
> I tried transferring to you, but got an error saying "AlexDaniel/z already exists "

Try again?

**Comment by AlexDaniel** [comment]
I have also sent you an invite to perl6 org. You don't need to accept it, and you can just leave it there in case you need it one day.

**Comment by zoffixznet** [comment]
"Repository transfer to AlexDaniel requested "

**Comment by AlexDaniel** [comment]
Thank you!
